---
layout: post
title: Current Dissertation Chapters and Thoughts on Missing Chapter Possibilities
date: '2026-06-24'
categories: [Dissertation, Chapters]
---
Post about current Dissertation Chapter Breakdown and thoughts on what the missing chapter could be!

# Current Chapters 
## Chapter 1 <-- Adults and Juveniles Exposed to SSWD Tissue Homogenates
### Current Status: Resubmitting to Wiley Nature and Ecology THIS FRIDAY

["A Comparison of Juvenile and Adult Sunflower Sea Star Transcriptomic Responses to Challenge with Sea Star Wasting Disease Tissue Homogenates"](https://docs.google.com/document/d/1ZsKS_qDDS_pUgQxMHfPGFfG0IPW5sRLhI6AqLMlm-_Q/edit?tab=t.0#heading=h.ge4t1be2hp7m)

## Chapter 2 <-- Multi-species Immune Response Comparison (exposure is co-housed with wasting _P. helianthoides_ injected with coelomic fluid from wasting _P. helianthoides_)       
### Current Status: Working on Results and [Draft](https://docs.google.com/document/d/1z5DrU6AJ1lJPsVdl30dVhYjqGvfV8RQ6fP03RT9tL28/edit?tab=t.0#heading=h.clbqxsygy87f)    
#### Goal --> finalize current results and draft this summer     

## Chapter 3 <-- ???? 
This is the Chapter that is up in the air. Some possibilities below. 

## Chapter 4 <-- Can eelgrass and/or mussels remove _V. pectenicida_ from sea water? Can eelgrass be refugia for _P. helianthoides_?     
### Current Status: [Drafting paper](https://docs.google.com/document/d/1QBI0xQn1SlM4TR-5Bx87Q_DtiLkACgV_b6Wlwp8SHJA/edit?tab=t.0#heading=h.41vbehuoswy0); this summer - 2026 sample processing and including results in draft 
#### Goal --> do 2026 lab work and draft this summer 

# Chapter 3 possibilities
## Option A:    
Microbes - who's there and what are they doing?    
I have DNA from all the RNAseq samples that I have sequenced that can be extracted and either sequenced for microbes or run on qPCR for _V. pectenicida_.     

This would pair nicely with the immune response work from Chapters 1 and 2 - or can just focus on Chapter 2 samples <-- see what microbes they are fighting against. Could be especially interesting for the _D. imbricata_ who had no outward signs of disease despite heavy exposure.    

## Option B:     
Immune response of _P. helianthoides_ exposed to _V. pectenicida_ culture (samples from [Prentice et al 2025](https://www.nature.com/articles/s41559-025-02797-2)).    

I have the coelomocyte samples from that summer! This would be the first data set looking at immune response from stars injected with _V. pectenicida_ culture!! And it would be a great companion paper to [Prentice et al 2025](https://www.nature.com/articles/s41559-025-02797-2).    

## Option C:    
Immune response of _P. helianthiodes_ to a dose response curve (experiment happening THIS SUMMER! Being run by Hakai folks at USGS Marrowstone and they said they could give me coelomocyte samples that they are going to take)!    

Would allow to look at **actual resistance** if some low-dose exposed _P. helianthoides_ don't die. And would also be data set of sea stars injected with _V. pectenicida_ culture. 
